name: Check build and test in all os
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        target:
          - linux-x86_64
          - windows-x86_64
          - macos-x86_64
        include:
          - target: linux-x86_64
            os: ubuntu-20.04
          - target: windows-x86_64
            os: windows-2019
          - target: macos-x86_64
            os: macos-11
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
      - name: Pip install
        run: pip install -r requirements.lock
      - name: Run Pyinstaller
        run: pyinstaller --onefile md2docx.py
      - name: Zip archive
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: md2docx-${{ matrix.target }}.zip
          directory: dist
      - name: Install for testing example in Ubuntu
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            patchelf \
            evince \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-fonts-recommended \
            texlive-lang-cjk \
            xdvik-ja \
            dvipng
      - name: Install for testing example in Macos
        if: ${{ contains(matrix.os, 'macos') }}
        run: |
          brew install --cask mactex-no-gui
      - name: Testing example
        run: ./dist/md2docx ./example/test1.md
