name: Make Release
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * ?
jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Check update
        run: |
          git fetch
          export UPDATED=$(git diff --name-only remotes/origin/release...remotes/origin/main | wc -l)
          echo "UPDATE_FILES_NUM=${UPDATED}" >> $GITHUB_ENV
          echo "detected ${UPDATED} updated files."
      - name: Merge
        if: ${{ env.UPDATE_FILES_NUM > 0 }}
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git merge remotes/origin/main
          git push origin release
        env:
          TZ: Asia/Tokyo
  publish:
    needs: update_branch
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Publish a draft release
        id: release
        uses: release-drafter/release-drafter@v5
        with:
          commitish: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
  build:
    needs: publish
    strategy:
      matrix:
        target:
          - linux-x86_64
          - windows-x86_64
          - macos-x86_64
        include:
          - target: linux-x86_64
            os: ubuntu-20.04
          - target: windows-x86_64
            os: windows-2019
          - target: macos-x86_64
            os: macos-11
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
      - name: Pip install
        run: pip install -r requirements.lock
      - name: Run Pyinstaller
        run: pyinstaller --onefile md2docx.py
      - name: Zip archive
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: md2docx-${{ matrix.target }}.zip
          directory: dist
      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.publish.outputs.upload_url }}
          asset_path: ./dist/md2docx-${{ matrix.target }}.zip
          asset_name: ./dist/md2docx-${{ matrix.target }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
