name: Make Release
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * ?
jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Check update
        run: |
          git fetch
          export UPDATED=$(git diff --name-only remotes/origin/release...remotes/origin/main | wc -l)
          echo "UPDATE_FILES_NUM=${UPDATED}" >> $GITHUB_ENV
          echo "detected ${UPDATED} updated files."
      - name: Merge
        if: ${{ env.UPDATE_FILES_NUM > 0 }}
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git merge remotes/origin/main
          git push origin release
        env:
          TZ: Asia/Tokyo
