name: Make Release
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * ?
jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Check update
        run: |
          git fetch
          echo "UPDATE_FILES_NUM=$(git diff --name-only refs/heads/main...refs/heads/release | wc -l)" >> $GITHUB_ENV
      - name: Merge
        if: ${{ env.UPDATE_FILES_NUM > 0 }}
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git merge refs/heads/main
          git push
        env:
          TZ: Asia/Tokyo
