name: Make Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Check update
        run: |
          git fetch
          export UPDATED=$(git diff --name-only remotes/origin/release...remotes/origin/main | wc -l)
          echo "UPDATE_FILES_NUM=${UPDATED}" >> $GITHUB_ENV
          echo "detected ${UPDATED} updated files."
      - name: Merge
        if: ${{ env.UPDATE_FILES_NUM > 0 }}
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
          git merge remotes/origin/main
          git push origin release
        env:
          TZ: Asia/Tokyo
  publish:
    needs: update_branch
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Publish a draft release
        id: release
        uses: release-drafter/release-drafter@v5
        with:
          commitish: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      tag_name: ${{ steps.release.outputs.tag_name }}
  build:
    needs: publish
    strategy:
      matrix:
        target:
          - linux-x86_64
          - windows-x86_64
          - macos-x86_64
        include:
          - target: linux-x86_64
            os: ubuntu-20.04
          - target: windows-x86_64
            os: windows-2019
          - target: macos-x86_64
            os: macos-11
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/release
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
      - name: Pip install
        run: pip install -r requirements.lock
      - name: Run Pyinstaller
        run: pyinstaller --onefile md2docx.py
      - name: Package for linux
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          cp config/md2docx-config.linux.yml dist/md2docx-config.yml
      - name: Package for windows
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          cp config/md2docx-config.windows.yml dist/md2docx-config.yml
      - name: Package for macos
        if: ${{ contains(matrix.os, 'macos') }}
        run: |
          cp config/md2docx-config.macos.yml dist/md2docx-config.yml
      - name: Zip archive
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: md2docx-${{ matrix.target }}.zip
          directory: dist
      - name: Upload release
        run: gh release upload ${{ needs.publish.outputs.tag_name }} ./dist/md2docx-${{ matrix.target }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
